# 连接池
Spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin

# mybatis 别名扫描
mybatis:
  type-aliases-package: com.demo.entity

